# Generated by Django 4.1.7 on 2023-04-25 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0009_client_customer_type_client_monthly_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sales_rep', models.CharField(blank=True, max_length=100, null=True)),
                ('total_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='client.client')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
