# Generated by Django 4.1.7 on 2023-04-26 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_client_customer_type_client_monthly_order_and_more'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
        migrations.AddField(
            model_name='report',
            name='customer_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('store', 'Store')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='unknown', max_length=225),
        ),
        migrations.AddField(
            model_name='report',
            name='org_name',
            field=models.CharField(default='unknown', max_length=225),
        ),
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_sales', to='client.client'),
        ),
    ]
